{-# LANGUAGE OverloadedStrings #-}

module Example.CountryEnum where

import Data.Text (Text)
import Prelude hiding (GT, LT)

data CountryEnum
  = AF | AX | AL | DZ | AS | AD | AO | AI | AG | AR | AM | AW | AU | AT | AZ
  | BS | BH | BD | BB | BY | BE | BZ | BJ | BM | BT | BO | BA | BW | BV | BR
  | VG | BN | BG | BF | MM | BI | TC | KH | CM | CA | CV | KY | CF | TD | CL
  | CN | CX | CC | CO | KM | CG | CD | CK | CR | CI | HR | CU | CY | CZ | DK
  | DJ | DM | DO | EC | EG | SV | GB | GQ | ER | EE | ET | EU | FK | FO | FJ
  | FI | FR | GF | PF | TF | GA | GM | GE | DE | GH | GI | GR | GL | GD | GP
  | GU | GT | GW | GN | GY | HT | HM | HN | HK | HU | IS | IN | IO | ID | IR
  | IQ | IE | IL | IT | JM | JP | JO | KZ | KE | KI | KW | KG | LA | LV | LB
  | LS | LR | LY | LI | LT | LU | MO | MK | MG | MW | MY | MV | ML | MT | MH
  | MQ | MR | MU | YT | MX | FM | MD | MC | MN | ME | MS | MA | MZ | NA | NR
  | NP | AN | NL | NC | PG | NZ | NI | NE | NG | NU | NF | KP | MP | NO | OM
  | PK | PW | PS | PA | PY | PE | PH | PN | PL | PT | PR | QA | RE | RO | RU
  | RW | SH | KN | LC | PM | VC | WS | SM | GS | ST | SA | SN | CS | RS | SC
  | SL | SG | SK | SI | SB | SO | ZA | KR | ES | LK | SD | SR | SJ | SZ | SE
  | CH | SY | TW | TJ | TZ | TH | TL | TG | TK | TO | TT | TN | TR | TM | TV
  | UG | UA | AE | US | UY | UM | VI | UZ | VU | VA | VE | VN | WF | EH | YE
  | ZM | ZW
  deriving (Bounded, Enum, Eq, Ord, Read, Show)

countryText :: CountryEnum -> Text
countryText AF = "Afghanistan"
countryText AX = "Aland Islands"
countryText AL = "Albania"
countryText DZ = "Algeria"
countryText AS = "American Samoa"
countryText AD = "Andorra"
countryText AO = "Angola"
countryText AI = "Anguilla"
countryText AG = "Antigua"
countryText AR = "Argentina"
countryText AM = "Armenia"
countryText AW = "Aruba"
countryText AU = "Australia"
countryText AT = "Austria"
countryText AZ = "Azerbaijan"
countryText BS = "Bahamas"
countryText BH = "Bahrain"
countryText BD = "Bangladesh"
countryText BB = "Barbados"
countryText BY = "Belarus"
countryText BE = "Belgium"
countryText BZ = "Belize"
countryText BJ = "Benin"
countryText BM = "Bermuda"
countryText BT = "Bhutan"
countryText BO = "Bolivia"
countryText BA = "Bosnia"
countryText BW = "Botswana"
countryText BV = "Bouvet Island"
countryText BR = "Brazil"
countryText VG = "British Virgin Islands"
countryText BN = "Brunei"
countryText BG = "Bulgaria"
countryText BF = "Burkina Faso"
countryText MM = "Burma"
countryText BI = "Burundi"
countryText TC = "Caicos Islands"
countryText KH = "Cambodia"
countryText CM = "Cameroon"
countryText CA = "Canada"
countryText CV = "Cape Verde"
countryText KY = "Cayman Islands"
countryText CF = "Central African Republic"
countryText TD = "Chad"
countryText CL = "Chile"
countryText CN = "China"
countryText CX = "Christmas Island"
countryText CC = "Cocos Islands"
countryText CO = "Colombia"
countryText KM = "Comoros"
countryText CG = "Congo Brazzaville"
countryText CD = "Congo"
countryText CK = "Cook Islands"
countryText CR = "Costa Rica"
countryText CI = "Cote Divoire"
countryText HR = "Croatia"
countryText CU = "Cuba"
countryText CY = "Cyprus"
countryText CZ = "Czech Republic"
countryText DK = "Denmark"
countryText DJ = "Djibouti"
countryText DM = "Dominica"
countryText DO = "Dominican Republic"
countryText EC = "Ecuador"
countryText EG = "Egypt"
countryText SV = "El Salvador"
countryText GB = "England"
countryText GQ = "Equatorial Guinea"
countryText ER = "Eritrea"
countryText EE = "Estonia"
countryText ET = "Ethiopia"
countryText EU = "European Union"
countryText FK = "Falkland Islands"
countryText FO = "Faroe Islands"
countryText FJ = "Fiji"
countryText FI = "Finland"
countryText FR = "France"
countryText GF = "French Guiana"
countryText PF = "French Polynesia"
countryText TF = "French Territories"
countryText GA = "Gabon"
countryText GM = "Gambia"
countryText GE = "Georgia"
countryText DE = "Germany"
countryText GH = "Ghana"
countryText GI = "Gibraltar"
countryText GR = "Greece"
countryText GL = "Greenland"
countryText GD = "Grenada"
countryText GP = "Guadeloupe"
countryText GU = "Guam"
countryText GT = "Guatemala"
countryText GW = "Guinea-Bissau"
countryText GN = "Guinea"
countryText GY = "Guyana"
countryText HT = "Haiti"
countryText HM = "Heard Island"
countryText HN = "Honduras"
countryText HK = "Hong Kong"
countryText HU = "Hungary"
countryText IS = "Iceland"
countryText IN = "India"
countryText IO = "Indian Ocean Territory"
countryText ID = "Indonesia"
countryText IR = "Iran"
countryText IQ = "Iraq"
countryText IE = "Ireland"
countryText IL = "Israel"
countryText IT = "Italy"
countryText JM = "Jamaica"
countryText JP = "Japan"
countryText JO = "Jordan"
countryText KZ = "Kazakhstan"
countryText KE = "Kenya"
countryText KI = "Kiribati"
countryText KW = "Kuwait"
countryText KG = "Kyrgyzstan"
countryText LA = "Laos"
countryText LV = "Latvia"
countryText LB = "Lebanon"
countryText LS = "Lesotho"
countryText LR = "Liberia"
countryText LY = "Libya"
countryText LI = "Liechtenstein"
countryText LT = "Lithuania"
countryText LU = "Luxembourg"
countryText MO = "Macau"
countryText MK = "Macedonia"
countryText MG = "Madagascar"
countryText MW = "Malawi"
countryText MY = "Malaysia"
countryText MV = "Maldives"
countryText ML = "Mali"
countryText MT = "Malta"
countryText MH = "Marshall Islands"
countryText MQ = "Martinique"
countryText MR = "Mauritania"
countryText MU = "Mauritius"
countryText YT = "Mayotte"
countryText MX = "Mexico"
countryText FM = "Micronesia"
countryText MD = "Moldova"
countryText MC = "Monaco"
countryText MN = "Mongolia"
countryText ME = "Montenegro"
countryText MS = "Montserrat"
countryText MA = "Morocco"
countryText MZ = "Mozambique"
countryText NA = "Namibia"
countryText NR = "Nauru"
countryText NP = "Nepal"
countryText AN = "Netherlands Antilles"
countryText NL = "Netherlands"
countryText NC = "New Caledonia"
countryText PG = "New Guinea"
countryText NZ = "New Zealand"
countryText NI = "Nicaragua"
countryText NE = "Niger"
countryText NG = "Nigeria"
countryText NU = "Niue"
countryText NF = "Norfolk Island"
countryText KP = "North Korea"
countryText MP = "Northern Mariana Islands"
countryText NO = "Norway"
countryText OM = "Oman"
countryText PK = "Pakistan"
countryText PW = "Palau"
countryText PS = "Palestine"
countryText PA = "Panama"
countryText PY = "Paraguay"
countryText PE = "Peru"
countryText PH = "Philippines"
countryText PN = "Pitcairn Islands"
countryText PL = "Poland"
countryText PT = "Portugal"
countryText PR = "Puerto Rico"
countryText QA = "Qatar"
countryText RE = "Reunion"
countryText RO = "Romania"
countryText RU = "Russia"
countryText RW = "Rwanda"
countryText SH = "Saint Helena"
countryText KN = "Saint Kitts and Nevis"
countryText LC = "Saint Lucia"
countryText PM = "Saint Pierre"
countryText VC = "Saint Vincent"
countryText WS = "Samoa"
countryText SM = "San Marino"
countryText GS = "Sandwich Islands"
countryText ST = "Sao Tome"
countryText SA = "Saudi Arabia"
countryText SN = "Senegal"
countryText CS = "Serbia"
countryText RS = "Serbia"
countryText SC = "Seychelles"
countryText SL = "Sierra Leone"
countryText SG = "Singapore"
countryText SK = "Slovakia"
countryText SI = "Slovenia"
countryText SB = "Solomon Islands"
countryText SO = "Somalia"
countryText ZA = "South Africa"
countryText KR = "South Korea"
countryText ES = "Spain"
countryText LK = "Sri Lanka"
countryText SD = "Sudan"
countryText SR = "Suriname"
countryText SJ = "Svalbard"
countryText SZ = "Swaziland"
countryText SE = "Sweden"
countryText CH = "Switzerland"
countryText SY = "Syria"
countryText TW = "Taiwan"
countryText TJ = "Tajikistan"
countryText TZ = "Tanzania"
countryText TH = "Thailand"
countryText TL = "Timorleste"
countryText TG = "Togo"
countryText TK = "Tokelau"
countryText TO = "Tonga"
countryText TT = "Trinidad"
countryText TN = "Tunisia"
countryText TR = "Turkey"
countryText TM = "Turkmenistan"
countryText TV = "Tuvalu"
countryText UG = "Uganda"
countryText UA = "Ukraine"
countryText AE = "United Arab Emirates"
countryText US = "United States"
countryText UY = "Uruguay"
countryText UM = "Us Minor Islands"
countryText VI = "Us Virgin Islands"
countryText UZ = "Uzbekistan"
countryText VU = "Vanuatu"
countryText VA = "Vatican City"
countryText VE = "Venezuela"
countryText VN = "Vietnam"
countryText WF = "Wallis and Futuna"
countryText EH = "Western Sahara"
countryText YE = "Yemen"
countryText ZM = "Zambia"
countryText ZW = "Zimbabwe"
